<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="8" total="11" passed="2">
  <reporter-output>
    <line>
      <![CDATA[Test succeed!!!]]>
    </line>
    <line>
      <![CDATA[Test Failed!!!]]>
    </line>
    <line>
      <![CDATA[Test succeed!!!]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="1163" started-at="2019-01-27T23:04:39Z" finished-at="2019-01-27T23:04:40Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="1163" started-at="2019-01-27T23:04:39Z" finished-at="2019-01-27T23:04:40Z">
      <class name="com.e2e.testcases.TC002">
        <test-method status="FAIL" signature="f()[pri:0, instance:com.e2e.testcases.TC002@17d677df]" name="f" duration-ms="217" started-at="2019-01-28T00:04:39Z" finished-at="2019-01-28T00:04:39Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at com.e2e.testcases.TC002.f(TC002.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test Failed!!!]]>
            </line>
          </reporter-output>
        </test-method> <!-- f -->
      </class> <!-- com.e2e.testcases.TC002 -->
      <class name="com.e2e.testcases.TC001">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.e2e.testcases.TC001@76b0bfab]" name="beforeMethod" is-config="true" duration-ms="7908" started-at="2019-01-28T00:04:31Z" finished-at="2019-01-28T00:04:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:com.e2e.testcases.TC001@76b0bfab]" name="beforeSuite" is-config="true" duration-ms="0" started-at="2019-01-28T00:04:39Z" finished-at="2019-01-28T00:04:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="f()[pri:0, instance:com.e2e.testcases.TC001@76b0bfab]" name="f" duration-ms="268" started-at="2019-01-28T00:04:39Z" finished-at="2019-01-28T00:04:39Z">
          <reporter-output>
            <line>
              <![CDATA[Test succeed!!!]]>
            </line>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.e2e.testcases.TC001@76b0bfab]" name="afterMethod" is-config="true" duration-ms="1077" started-at="2019-01-28T00:04:40Z" finished-at="2019-01-28T00:04:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:com.e2e.testcases.TC001@76b0bfab]" name="afterSuite" is-config="true" duration-ms="1" started-at="2019-01-28T00:04:41Z" finished-at="2019-01-28T00:04:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.e2e.testcases.TC001 -->
      <class name="com.e2e.testcases.TC003">
        <test-method status="PASS" signature="f()[pri:0, instance:com.e2e.testcases.TC003@3043fe0e]" name="f" duration-ms="223" started-at="2019-01-28T00:04:40Z" finished-at="2019-01-28T00:04:40Z">
          <reporter-output>
            <line>
              <![CDATA[Test succeed!!!]]>
            </line>
          </reporter-output>
        </test-method> <!-- f -->
      </class> <!-- com.e2e.testcases.TC003 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
